config/routes.rb
Rails.application.routes.draw do
  resources :recurrables
  resources :tags
  resources :entries
  post '/filtered_entries', to: 'entries#filtered_index'
  get '/export/entries', to: 'entries#export'

  resources :categories do
    delete 'remove', on: :member
  end
  get '/merge_categories', to: 'categories#merge_form'
  post '/merge_categories', to: 'categories#merge'

  # Dashboard
  get '/dashboard', to: 'dashboards#show'
  post '/dashboard', to: 'dashboards#show'
  post '/turbo_charts/:chart_name', to: 'dashboards#charts', as: 'chart'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'entries#new', as: :authenticated_root
    end

    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  if Rails.configuration.database_configuration[Rails.env]['database'] == 'sum_test'
    get '/clear_db', to: 'test#clear_db'
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  include Taggable

  belongs_to :user
  belongs_to :category

  scope :by_year, -> (year) { where('extract(year from date) = ?', year) if year.present? }
  scope :by_month, -> (month) { where('extract(month from date) = ?', month) unless month.blank? || month.to_i.zero? }
  scope :by_income, -> (income) { joins(:category).where(categories: { income: income }) if !!income == income }
  scope :by_untracked, -> (untracked) { joins(:category).where(categories: { untracked: untracked }) if !!untracked == untracked }
  scope :by_category_id, -> (category_id) { where(category_id: category_id) if category_id.present? }
  scope :by_tag_id, -> (tag_id) { where(tag_id: tag_id) if tag_id.present? }
end

app/controllers/entries_controller.rb
require 'csv'

class EntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = current_user.entries
                                   .by_year(session[:entry_filter_year] || Date.today.year)
                                   .by_month(session[:entry_filter_month] || Date.today.month)
                                   .by_income(ActiveModel::Type::Boolean.new.cast(session[:entry_filter_income]))
                                   .by_category_id(session[:entry_filter_category_id])
                                   .by_tag_id(session[:entry_filter_tag_id])
                                   .includes(:category)
    @years = current_user.entries.order(:date).pluck(:date).uniq { |d| d.year }.map(&:year)
    @categories = current_user.categories
    @tags = current_user.tags
  end

  # POST /filtered_entries
  def filtered_index
    set_session_filters
    @categories = current_user.categories
    @tags = current_user.tags
    @entries = current_user.entries
                           .by_year(params['year'])
                           .by_month(params['month'])
                           .by_income(ActiveModel::Type::Boolean.new.cast(params['income']))
                           .by_category_id(params['category_id'])
                           .by_tag_id(params['tag_id'])
                           .includes(:category)

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.replace(:entries, partial: "entries", locals: { entries: @entries }) }
    end
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
    @entry.build_tag
    @categories = current_user.categories
  end

  # GET /entries/1/edit
  def edit
    @categories = current_user.categories
    @entry.build_tag unless @entry.tag
  end

  # POST /entries
  def create
    @entry = Entry.new(entry_params)
    @entry.user = current_user

    if @entry.save
      redirect_to new_entry_url, notice: "Entry was successfully created."
    else
      @categories = current_user.categories
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /entries/1
  def update
    if @entry.update(entry_params)
      redirect_to entry_url(@entry), notice: "Entry was successfully updated."
    else
      @categories = current_user.categories
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /entries/1
  def destroy
    @entry.destroy
    redirect_to entries_url, notice: "Entry was successfully destroyed."
  end

  # GET /entries/export
  def export
    @entries = current_user.entries
    respond_to do |format|
      format.csv do
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = "attachment; filename=entries.csv"
        render 'export'
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = current_user.entries.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to entries_url, notice: "Entry not found."
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:date, :amount, :notes, :category_name, :income, :untracked, :user_id, :category_id, tag_attributes: [:id, :name, :_destroy])
    end

    def set_session_filters
      session[:entry_filter_category_id] = params['category_id']
      session[:entry_filter_tag_id] = params['tag_id']
      session[:entry_filter_year] = params['year']
      session[:entry_filter_month] = params['month']
      session[:entry_filter_income] = params['income']
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_dashboard_data.html.haml
%div#data
  %h2 Totals
  .row
    .col-sm-6
      .card.text-dark.bg-light
        .card-body
          %h5.card-title Total Spending
          %p.card-text= number_to_currency(@data.total_spending)
    .col-sm-6
      .card.text-dark.bg-light
        .card-body
          %h5.card-title Total Income
          %p.card-text= number_to_currency(@data.total_income)
  %hr
  %h2 Categories
  .row.rows-cols-auto.g-2
    - @data.category_totals.each do |category, total|
      .col
        .card.text-dark.bg-light
          .card-body
            %h5.card-title= category
            %p.card-text= number_to_currency(total)
  %h2 Pie
  = pie_chart @data.category_totals

app/views/entries/_entries.html.haml
%div#entries.data-table-wrapper{ 'data-controller' => 'data-table' }
  %table.table.hover
    %thead
      %tr
        %th{scope: "col"} Date
        %th{scope: "col"} Amount
        %th{scope: "col"} Category
        %th{scope: "col"} Notes
    %tbody
      - @entries.each do |entry|
        %tr.clickable-row{ 'data-href': entry_url(entry) }
          %td= entry.date
          %td= entry.amount
          %td= entry.category.name
          %td= entry.notes

app/views/entries/_form.html.haml
= form_for @entry do |f|
  - if @entry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@entry.errors.count, "error")} prohibited this entry from being saved:"
      %ul
        - @entry.errors.full_messages.each do |message|
          %li= message

  .field.mb-3{ 'data-controller': 'date-picker' }
    = f.label :date, { class: 'form-label' }
    = f.date_field :date, { class: 'form-control', id: "#{@entry.id ? '' : 'date-picker'}" }
  .field.mb-3
    = f.label :amount, { class: 'form-label' }
    = f.number_field :amount, { class: 'form-control', placeholder: '$0.00', step: '.01', inputmode: "decimal" }
  .field.mb-3
    = f.label :notes, { class: 'form-label' }
    = f.text_area :notes, { class: 'form-control' }
  .field.mb-3
    = f.label :category, { class: 'form-label' }
    = f.collection_select :category_id, @categories, :id, :name, { include_blank: true }, { class: 'form-select' }
  .field.mb-3{ 'data-controller': 'tag' }
    = f.fields_for :tag do |nested_form|
      = nested_form.label :name, 'Tag', { class: 'form-label' }
      %div.d-flex.justify-content-between
        = nested_form.text_field :name, { id: 'tag', class: 'form-control me-5' }
        = nested_form.hidden_field :_destroy, { id: 'tag-destroy' }
        %button.btn.btn-danger{ id: 'destroy-btn', class: "#{'invisible' unless @entry.tag_id}", data: { action: "click->tag#remove:prevent" } } Remove
        %button.btn.btn-primary.invisible{ id: 'restore-btn', data: { action: "click->tag#restore:prevent" } } Restore
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/entries/dashboard.html.haml
%h1 Dashboard
= turbo_frame_tag 'filter' do
  = form_with(url: '/dashboard') do |f|
    %div.mb-3
      = f.label :month, 'Month',  class: 'form-label'
      = f.select :month, options_for_select(Date::MONTHNAMES.zip(0..12)), {}, class: 'form-select d-inline-block', style: 'width:auto;'
      = f.label :year, 'Year', class: 'form-label'
      = f.select :year, options_for_select(@years), { include_blank: true }, class: 'form-select d-inline-block', style: 'width:auto;'
    = f.submit "Filter", class: 'btn btn-primary'
%div#data
  = render partial: "dashboard_data", locals: { data: @data }

app/views/entries/edit.html.haml
%h1 Editing entry

= render 'form'

= link_to 'Show', @entry
\|
= link_to 'Back', entries_path

app/views/entries/export.csv.haml
- headers = ['Date', 'Amount', 'Category', 'Notes']
= CSV.generate_line headers
- @entries.each do |entry|
  = CSV.generate_line([entry.date, entry.amount, entry.category.name, entry.notes])

app/views/entries/index.html.haml
%h1 Entries
%a.btn.btn-primary.mb-3{ href: new_entry_path }
  %i.bi.bi-plus-circle-fill
  New Entry
%br
= form_with(url: '/filtered_entries') do |f|
  %div.mb-3
    = f.label :month, 'Month',  class: 'form-label'
    = f.select :month, options_for_select(Date::MONTHNAMES.zip(0..12), session[:entry_filter_month] || Date.today.month), {}, class: 'form-select d-inline-block', style: 'width:auto;'
    = f.label :year, 'Year', class: 'ms-3 form-label'
    = f.select :year, options_for_select(@years, session[:entry_filter_year] || Date.today.year), { include_blank: true }, class: 'form-select d-inline-block me-4', style: 'width:auto;'
  %div.mb-3
    = f.label :income, 'Income', class: 'form-label'
    = f.select :income, options_for_select([true, false], session[:entry_filter_income]), { include_blank: true }, class: 'form-select d-inline-block', style: 'width:auto;'
    = f.label :tag_id, 'Tag', class: 'ms-3 form-label'
    = f.collection_select :tag_id, @tags, :id, :name, { include_blank: true, placeholder: 'all', selected: session[:entry_filter_tag_id] }, class: 'form-select d-inline-block', style: 'width:auto;'
  %div.mb-3
    = f.label :category_id, 'Category', class: 'form-label'
    = f.collection_select :category_id, @categories, :id, :name, { include_blank: true, placeholder: 'all', selected: session[:entry_filter_category_id] }, class: 'form-select d-inline-block', style: 'width:auto;'
  = f.submit "Filter", class: 'btn btn-primary'

= render partial: "entries", locals: { entries: @entries }

app/views/entries/new.html.haml
%h1 New entry

= render 'form'

app/views/entries/show.html.haml
%p
  %b Date:
  = @entry.date
%p
  %b Amount:
  = @entry.amount
%p
  %b Notes:
  = @entry.notes
%p
  %b Category:
  = @entry.category.name
%p
  %b Tag:
  = @entry&.tag&.name
%p
  %b Income:
  = @entry.category.income
%p
  %b Untracked:
  = @entry.category.untracked

= link_to 'Edit', edit_entry_path(@entry), class: 'btn btn-primary'
\|
= link_to 'Back', entries_path, class: 'btn btn-primary'
\|
= link_to 'Destroy', entry_path(@entry), class: 'btn btn-primary', data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure you want to delete this?' }