config/routes.rb
Rails.application.routes.draw do
  resources :recurrables
  resources :tags
  resources :entries
  post '/filtered_entries', to: 'entries#filtered_index'
  get '/export/entries', to: 'entries#export'

  resources :categories do
    delete 'remove', on: :member
  end
  get '/merge_categories', to: 'categories#merge_form'
  post '/merge_categories', to: 'categories#merge'

  # Dashboard
  get '/dashboard', to: 'dashboards#show'
  post '/dashboard', to: 'dashboards#show'
  post '/turbo_charts/:chart_name', to: 'dashboards#charts', as: 'chart'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'entries#new', as: :authenticated_root
    end

    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  if Rails.configuration.database_configuration[Rails.env]['database'] == 'sum_test'
    get '/clear_db', to: 'test#clear_db'
  end
end

app/models/recurrable.rb
class Recurrable < ApplicationRecord
  include Taggable
  belongs_to :category
  belongs_to :user

  serialize :schedule

  def day_of_month=(num)
    schedule = IceCube::Schedule.new(Date.today)
    schedule.add_recurrence_rule IceCube::Rule.monthly.day_of_month(num.to_i)
    write_attribute(:day_of_month, num.to_i)
    write_attribute(:schedule, schedule.to_yaml)
    write_attribute(:schedule_string, schedule.to_s)
  end

  def schedule
    IceCube::Schedule.from_yaml(read_attribute(:schedule))
  end

  def self.create_occurrences
    where(day_of_month: Date.today.day).each do |recurrable|
      unless Entry.where(user_id: recurrable.user_id, category_id: recurrable.category_id, date: Date.today, amount: recurrable.amount, notes: recurrable.notes).exists?
        recurrable.create_occurrence
      end
    end
  end

  def create_occurrence
    Entry.create!(
      date: Date.today,
      amount: amount,
      notes: notes,
      category_id: category_id,
      user_id: user_id,
      tag_id: tag_id
    )
  end
end

app/controllers/recurrables_controller.rb
class RecurrablesController < ApplicationController
  before_action :set_recurrable, only: %i[ show edit update destroy ]

  # GET /recurrables
  def index
    @recurrables = current_user.recurrables
  end

  # GET /recurrables/1
  def show
  end

  # GET /recurrables/new
  def new
    @recurrable = Recurrable.new
    @recurrable.build_tag
    @categories = current_user.categories
  end

  # GET /recurrables/1/edit
  def edit
    @categories = current_user.categories
    @recurrable.build_tag unless @recurrable.tag
  end

  # POST /recurrables
  def create
    @recurrable = Recurrable.new(recurrable_params)
    @recurrable.user = current_user

    if @recurrable.save
      redirect_to recurrable_url(@recurrable), notice: "Recurrable was successfully created."
    else
      @categories = current_user.categories
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /recurrables/1
  def update
    if @recurrable.update(recurrable_params)
      redirect_to recurrable_url(@recurrable), notice: "Recurrable was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /recurrables/1
  def destroy
    @recurrable.destroy
    redirect_to recurrables_url, notice: "Recurrable was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recurrable
      @recurrable = current_user.recurrables.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to recurrables_url, notice: "Recurrable not found."
    end

    # Only allow a list of trusted parameters through.
    def recurrable_params
      params.require(:recurrable).permit(:name, :day_of_month, :amount, :notes, :category_id, tag_attributes: [:id, :name, :_destroy ])
    end
end

app/views/recurrables/_form.html.haml
= form_for @recurrable do |f|
  - if @recurrable.errors.any?
    #error_explanation
      %h2= "#{pluralize(@recurrable.errors.count, "error")} prohibited this recurrable from being saved:"
      %ul
        - @recurrable.errors.full_messages.each do |message|
          %li= message

  .field.mb-3
    = f.label :name, { class: 'form-label' }
    = f.text_field :name
  .field.mb-3
    = f.label :day_of_month, { class: 'form-label' }
    = f.select :day_of_month, (1..31), { class: 'form-select' }
  .field.mb-3
    = f.label :amount, { class: 'form-label' }
    = f.number_field :amount, { class: 'form-control', placeholder: '$0.00', step: '.01', inputmode: "decimal" }
  .field.mb-3
    = f.label :notes, { class: 'form-label' }
    = f.text_area :notes, { class: 'form-control' }
  .field.mb-3
    = f.label :category, { class: 'form-label' }
    = f.collection_select :category_id, @categories, :id, :name, { include_blank: true }, { class: 'form-select' }
  .field.mb-3{ 'data-controller': 'tag' }
    = f.fields_for :tag do |nested_form|
      = nested_form.label :name, 'Tag', { class: 'form-label' }
      %div.d-flex.justify-content-between
        = nested_form.text_field :name, { id: 'tag', class: 'form-control me-5' }
        = nested_form.hidden_field :_destroy, { id: 'tag-destroy' }
        %button.btn.btn-danger{ id: 'destroy-btn', class: "#{'invisible' unless @recurrable.tag_id}", data: { action: "click->tag#remove:prevent" } } Remove
        %button.btn.btn-primary.invisible{ id: 'restore-btn', data: { action: "click->tag#restore:prevent" } } Restore
  .actions
    = f.submit 'Save'

app/views/recurrables/edit.html.haml
%h1 Editing recurrable

= render 'form'

= link_to 'Show', @recurrable
\|
= link_to 'Back', recurrables_path

app/views/recurrables/index.html.haml
%h1 Recurring Entries

%a.btn.btn-primary{ href: new_recurrable_path }
  %i.bi.bi-plus-circle-fill
  New Recurring Entry

%div.data-table-wrapper{ 'data-controller' => 'data-table' }
%table.table.hover
  %thead
    %tr
      %th Name
      %th Amount
      %th Category
      %th Day of Month

  %tbody
    - if @recurrables.any?
      - @recurrables.each do |recurrable|
        %tr.clickable-row{ 'data-href' => recurrable_path(recurrable) }
          %td= recurrable.name
          %td= recurrable.amount
          %td= recurrable.category.name
          %td= recurrable.day_of_month
    - else
      %tr
        %td
          No recurring entries found.
        %td
        %td
        %td

app/views/recurrables/new.html.haml
%h1 New recurrable

= render 'form'

= link_to 'Back', recurrables_path

app/views/recurrables/show.html.haml
%h2 Recurring Expense
%p
  %b Name:
  = @recurrable.name
%p
  %b Schedule:
  = @recurrable.schedule_string
%p
  %b Amount:
  = @recurrable.amount
%p
  %b Notes:
  = @recurrable.notes
%p
  %b Category:
  = @recurrable.category.name
%p
  %b Tag:
  = @recurrable.tag&.name

= link_to 'Edit', edit_recurrable_path(@recurrable), class: 'btn btn-primary'
= link_to 'Back', recurrables_path, class: 'btn btn-primary'
= link_to 'Destroy', recurrable_path(@recurrable), class: 'btn btn-primary', data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure you want to delete this?' }