config/routes.rb
Rails.application.routes.draw do
  resources :recurrables
  resources :tags
  resources :entries
  post '/filtered_entries', to: 'entries#filtered_index'
  get '/export/entries', to: 'entries#export'

  resources :categories do
    delete 'remove', on: :member
  end
  get '/merge_categories', to: 'categories#merge_form'
  post '/merge_categories', to: 'categories#merge'

  # Dashboard
  get '/dashboard', to: 'dashboards#show'
  post '/dashboard', to: 'dashboards#show'
  post '/turbo_charts/:chart_name', to: 'dashboards#charts', as: 'chart'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'entries#new', as: :authenticated_root
    end

    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  if Rails.configuration.database_configuration[Rails.env]['database'] == 'sum_test'
    get '/clear_db', to: 'test#clear_db'
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags
  def index
    @tags = current_user.tags
  end

  # GET /tags/1
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to tag_url(@tag), notice: "Tag was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
      redirect_to tags_url, notice: "Tag was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tags/1
  def destroy
    Entry.where(tag_id: @tag.id).update_all(tag_id: nil)
    @tag.destroy

    redirect_to tags_url, notice: "Tag was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = current_user.tags.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to tags_url, notice: "Tag not found."
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/views/tags/_form.html.haml
= form_for @tag do |f|
  - if @tag.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      %ul
        - @tag.errors.full_messages.each do |message|
          %li= message
  .field.mb-3
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .actions
    = f.submit 'Save'

app/views/tags/edit.html.haml
%h1 Editing tag

= render 'form'

= link_to 'Show', @tag
\|
= link_to 'Back', tags_path

app/views/tags/index.html.haml
%h1 Tags

%div.data-table-wrapper{ 'data-controller' => 'data-table' }
%table.table.hover.no-sum
  %thead
    %tr
      %th{scope: "col"} Name
      %th{scope: "col"} Created
      %th{scope: "col"}
  %tbody
    - @tags.each do |tag|
      %tr
        %td= tag.name
        %td= tag.created_at
        %td
          = link_to 'Edit', edit_tag_path(tag), class: 'btn btn-primary'
          = link_to 'Delete', tag_path(tag), data: { 'turbo-method': :delete, 'turbo-confirm': "Are you sure? This will remove the tag from #{Entry.where(tag_id: tag.id).count} entries." }, class: 'btn btn-danger'