config/routes.rb
Rails.application.routes.draw do
  resources :recurrables
  resources :tags
  resources :entries
  post '/filtered_entries', to: 'entries#filtered_index'
  get '/export/entries', to: 'entries#export'

  resources :categories do
    delete 'remove', on: :member
  end
  get '/merge_categories', to: 'categories#merge_form'
  post '/merge_categories', to: 'categories#merge'

  # Dashboard
  get '/dashboard', to: 'dashboards#show'
  post '/dashboard', to: 'dashboards#show'
  post '/turbo_charts/:chart_name', to: 'dashboards#charts', as: 'chart'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'entries#new', as: :authenticated_root
    end

    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  if Rails.configuration.database_configuration[Rails.env]['database'] == 'sum_test'
    get '/clear_db', to: 'test#clear_db'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :users
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[ show edit update remove destroy ]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        current_user.categories << @category
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1/remove
  def remove
    current_user.categories.delete(@category)

    redirect_to categories_url, notice: "Category was successfully removed."
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # GET /categories/merge
  def merge_form
    @categories = current_user.categories.order(created_at: :asc)
    @tags = current_user.tags
  end

  # POST /categories/merge
  # Copy all entries from one category to another and remove the old category
  def merge
    @old_category = current_user.categories.find(merge_params[:id])
    @merge_with = current_user.categories.find(merge_params[:merge_with])
    if merge_params[:tag_id].present?
      @tag = current_user.tags.find(merge_params[:tag_id])
    elsif merge_params[:tag_name].present?
      @tag = current_user.tags.find_or_create_by(name: merge_params[:tag_name])
    end
    ActiveRecord::Base.transaction do
      entries = Entry.where(category: @old_category)
      entries.update_all(category_id: @merge_with.id, tag_id: @tag&.id)
      @old_category.destroy
    end
    redirect_to merge_categories_path, notice: "Category was successfully merged."

  rescue ActiveRecord::RecordInvalid => e
    redirect_to merge_categories_path, alert: "There was an error. Category could not be merged."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = current_user.categories.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to categories_url, alert: "Category not found."
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :income, :untracked)
    end

    def merge_params
      params.permit(:id, :merge_with, :tag_id, :tag_name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.haml
%div{:id => "#{dom_id category}"}
  %p
    %strong Name:
    = category.name
  %p
    %strong Income:
    = category.income
  %p
    %strong Untracked:
    = category.untracked

app/views/categories/_form.html.haml
= form_with(model: category) do |form|
  - if category.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(category.errors.count, "error")
        prohibited this category from being saved:
      %ul
        - category.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :name, style: "display: block"
    = form.text_field :name
  %div
    = form.label :income, style: "display: block"
    = form.check_box :income
  %div
    = form.label :untracked, style: "display: block"
    = form.check_box :untracked
  %div
    = form.submit

app/views/categories/edit.html.haml
%h1 Editing category
= render "form", category: @category
%br/
%div
  = link_to "Show this category", @category
  |
  \#{link_to "Back to categories", categories_path}

app/views/categories/index.html.haml
%h1 Categories
%a.btn.btn-primary{ href: new_category_path }
  %i.bi.bi-plus-circle-fill
  New Category
%a.btn.btn-primary{ href: merge_categories_path }
  %i.bi.bi-plus-circle-fill
  Merge Categories
%div.data-table-wrapper{ 'data-controller' => 'data-table' }
%table.table.hover.no-sum
  %thead
    %tr
      %th{scope: "col"} Name
      %th{scope: "col"} Income
      %th{scope: "col"} Untracked
  %tbody
    - @categories.each do |category|
      %tr.clickable-row{ 'data-href': category_url(category) }
        %td= category.name
        %td= category.income
        %td= category.untracked

app/views/categories/merge_form.html.haml
%div
  = form_with url: merge_categories_path, method: :post do |f|
    %div.d-flex.flex-column.align-items-center
      = f.label :id, "I want to merge Category:"
      = f.select :id, options_for_select(@categories.map { |c| ["#{c.name}", c.id] }), include_blank: true
    %div.d-flex.flex-column.align-items-center
      = f.label :merge_with, "Into Category:"
      = f.select :merge_with, options_for_select(@categories.map { |c| ["#{c.name}", c.id] }), include_blank: true
    %div.d-flex.flex-column.align-items-center
      = f.label :tag_id, "and mark the entries with the following tag:"
      %div
        = f.select :tag_id, options_for_select(@tags.map { |t| [t.name, t.id] }), include_blank: true
        = f.text_field :tag_name, placeholder: "or create a new tag"
    %div.d-flex.flex-column.align-items-center
      = f.submit 'Merge'

app/views/categories/new.html.haml
%h1 New category
= render "form", category: @category
%br/
%div
  = link_to "Back to categories", categories_path

app/views/categories/show.html.haml
= render @category
%div
  = link_to "Edit this category", edit_category_path(@category), class: "btn btn-primary"
%br
  = link_to "Back to categories", categories_path, class: "btn btn-primary"
%br
  = link_to "Remove", remove_category_path(@category), class: "btn btn-primary", data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure you want to remove this?' }